import type { Metadata } from "next";
import "@/styles/globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-row justify-around">
      <nav className=" items-center  flex-wrap p-6 w-1/5">
        レイアウト02
        <div className="block lg:hidden"></div>
        <div className="text-sm ">
          <Link
            className=" text-blue-300 hover:text-white "
            href="/root-account/"
          >
            root-account
          </Link>
          <br />
          <Link
            className=" text-blue-300 hover:text-white "
            href="/root-account/test01"
          >
            test01
          </Link>
          <br />
          <Link
            className="  text-blue-300 hover:text-white "
            href="/root-account/test02"
          >
            test02
          </Link>
          <br />
          <Link
            className=" text-blue-300 hover:text-white "
            href="/root-account/test03"
          >
            test03
          </Link>
          <br />
          {/* TOPページへ */}
          <Link href="/">TOPページへ</Link>
        </div>
      </nav>
      <div className="w-4/5 gap-4">{children}</div>
    </div>
  );
}
