import type { Metadata } from "next";
import "@/styles/globals.css";
import Link from "next/link";

import Header from "@/app/common/nav/header";
import Footer from "@/app/common/nav/footer";
import { CategoryLinks } from "@/app/components/nav-link/CategoryLinks";
import { RootAccount } from "@/app/components/nav-link/RootAccounts";
import { UserProfiles } from "@/app/components/nav-link/UserProfiles";
import { List } from "@/app/components/nav-link/List";
import Footer from "@/app/common/nav/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      レイアウト02
      <Header />
      <div className="flex flex-row ">
        <nav className="w-1/5">
          <RootAccount />
          <UserProfiles />
          <CategoryLinks />
          <List />
          {/* TOPページへ */}
          <Link href="/">TOPページへ</Link>
        </nav>
        <div className="w-4/5">{children}</div>
      </div>
      <Footer />
    </div>
  );
}
