import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 何も装飾をしない
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      レイアウト01
      {children}
    </>
  );
}
